apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    chart: {{ template "kritis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["--tls-cert-file=/var/tls/cert",
               "--tls-key-file=/var/tls/key", 
               "--cron-interval=1m",
               "--logtostderr"]
        ports:
          - name: https
            containerPort: 8443
            protocol: TCP
        volumeMounts:
        - mountPath: /var/tls
          name: tls
        - name: {{ .Values.secret.name }}
          mountPath: /secret
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/{{ .Values.secret.path }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tlsSecretName }}
        - name: {{ .Values.secret.name }}
          secret:
            secretName: {{ .Values.secret.name }}
