# Default values for kritis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: v0.2.1
  image: kritis-server
  name: kritis-server
  pullPolicy: Always

service:
  type: ClusterIP
  port: 443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceName: kritis-validation-hook
serviceLabel: kritis-validation-hook
serviceNamePods: kritis-validation-hook
serviceNameDeployments: kritis-validation-hook-deployments
tlsSecretName: tls-webhook-secret
csrName: tls-webhook-secret-cert
clusterRoleBindingName: kritis-clusterrolebinding
clusterRoleName: kritis-clusterrole

kritisInstallLabel: "kritis.grafeas.io/install"

repository: gcr.io/kritis-project/

# kritis-server-webhook.yaml values
caBundle: ""
serviceNamespace: "default"

gacSecret:
  name: "gac-ca-admin"
  path: "gac.json"

preinstall:
  serviceAccount: "kritis-preinstall-serviceaccount"
  clusterRoleBinding: "kritis-preinstall-clusterrolebinding"
  createNewCSR: "--create-new-csr=true"
  pod:
    name: "kritis-preinstall"
    image: preinstall
    command: ["/preinstall"]

postinstall:
  pod:
    name: "kritis-postinstall"
    image: postinstall
    command: ["/postinstall"]


predelete:
  deleteCSR: "--delete-csr=true"
  deleteCRDs: "--delete-crd=true"
  pod:
    name: "kritis-predelete"
    image: predelete
    command: ["/predelete"]

# Certificates for Grafeas mutual authentication
certificates:
  name: kritis-ssl-certs
  ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
